title: 'args'
description: 'Type-safe argument parser for modern C++'
author:
  name: 'Dominik Lohmann'
  mail: 'mail@dominiklohmann.de'
  github_username: 'dominiklohmann'
remote_theme: pmarsceill/just-the-docs
color_scheme: dark
search_enabled: true
# These files have a specific meaning for GitHub repositories, so we have to
# include them explicitly.
include:
  - 'code_of_conduct.md'
  - 'contributing.md'
  - 'security.md'
